/**
 *    This code was generated by JSTP CodeGen version 1.0.0.20637
 *
 *    Generate info:
 *        Date      : 15.09.2015 11:27
 *        User      : voloshkevich
 *        Domain    : RTS
 *  Paths:
 *
 *      ======== Device info ========
 *      info: DeviceInfo 1.0.0
 *        info.company : Company name
 *        info.name : Model name
 *        info.sn : Serial number
 *        info.date : Production date
 *        info.sv : Firmware version
 *        info.hv : Hardware version
 *        info.title : Device title
 *        info.desc : Description
 *
 *      ======== Test interface ========
 *      test: Test 1.0.0
 *        test.int : u8 -> u8
 *        test.real : Real -> Real
 *        test.enum : enum -> enum
 *        test.bool : bool -> bool
 *        test.obj : obj -> obj
 *        test.arrBool : arrBool -> arrBool
 *        test.intArr : intArr -> intArr
 *        test.realArr : realArr -> realArr
 *        test.strArr : strArr -> strArr
 *        test.enumArr : enumArr -> enumArr
 *        test.objArr : objArr -> objArr
 *        test.arrArr : arrArr -> arrArr
*/

#include "jstp_gen.h"

//======================================================================
//
//                  Device info
// 
//======================================================================

/**
 * info.company
 * Company name
 * Arg      : NULL
 * Result   : String
 */
static int jstp_info_company(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- String
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.name
 * Model name
 * Arg      : NULL
 * Result   : String
 */
static int jstp_info_name(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- String
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.sn
 * Serial number
 * Arg      : NULL
 * Result   : SerialNumber
 */
static int jstp_info_sn(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- SerialNumber
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.date
 * Production date
 * Arg      : NULL
 * Result   : DateTime
 */
static int jstp_info_date(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- DateTime
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.sv
 * Firmware version
 * Arg      : NULL
 * Result   : Version
 */
static int jstp_info_sv(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- Version
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.hv
 * Hardware version
 * Arg      : NULL
 * Result   : Version
 */
static int jstp_info_hv(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- Version
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.title
 * Device title
 * Arg      : NULL
 * Result   : String
 */
static int jstp_info_title(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- String
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * info.desc
 * Description
 * Arg      : NULL
 * Result   : String
 */
static int jstp_info_desc(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======
   // Null

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_str(<str>);       // <- String
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}



//======================================================================
//
//                  Test interface
// 
//======================================================================

/**
 * test.int
 * u8 -> u8
 * Arg      : u8
 * Result   : u8
 */
static int jstp_test_int(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    long longArg;
    if (!jstp_rx_long(arg_str,arg_tokens,&longArg)) return JSTP_ARGS_ERROR;

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    // jstp_tx_int(<long>);        // <- u8
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.real
 * Real -> Real
 * Arg      : Real
 * Result   : Real
 */
static int jstp_test_real(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    float value;
    if (!jstp_rx_float(arg_str,arg_tokens,&value)) return JSTP_ARGS_ERROR;

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // jstp_tx_float(<float>);        // <- Real
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.enum
 * enum -> enum
 * Arg      : enumType
 * Result   : enumType2
 */
static int jstp_test_enum(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    if (jstp_rx_cmp_str(arg_str,arg_tokens,"item1")) // <- item21
    {
        // item21
    }
    else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item2")) // <- item22
    {
        // item22
    }
    else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item3")) // <- item23
    {
        // item23
    }
    else return JSTP_ARGS_ERROR; 

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":
    jstp_tx_str("item1");       // <- item21
    //jstp_tx_str("item2");       // <- item22
    //jstp_tx_str("item3");       // <- item23
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.bool
 * bool -> bool
 * Arg      : Bool
 * Result   : Bool
 */
static int jstp_test_bool(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    int boolArg;
    if (!jstp_rx_bool(arg_str,arg_tokens,&boolArg)) return JSTP_ARGS_ERROR;
    if (boolArg)
    {
        // true
    }else
    {
        // false
    };

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // jstp_tx_bool(<int>);        // <- Bool
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.obj
 * obj -> obj
 * Arg      : objType
 * Result   : objType
 */
static int jstp_test_obj(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // objType
    size_t size;
    if (!jstp_rx_obj(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // objType.p_bool
        if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_bool")) 
        {

            int boolArg;
            if (!jstp_rx_bool(arg_str,++arg_tokens,&boolArg)) return JSTP_ARGS_ERROR;
            if (boolArg)
            {
                // true
            }else
            {
                // false
            };

        }
        // objType.p_int
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_int"))
        {

            long intArg;
            if (!jstp_rx_long(arg_str,++arg_tokens,&intArg)) return JSTP_ARGS_ERROR;

        }
        // objType.p_real
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_real"))
        {

            float value;
            if (!jstp_rx_float(arg_str,++arg_tokens,&value)) return JSTP_ARGS_ERROR;
            

        }
        // objType.p_str
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_str"))
        {
            // string
            char * str;
            size_t str_len;
            if (!jstp_rx_str(arg_str,++arg_tokens,&str,&str_len)) return JSTP_ARGS_ERROR;
            // WARNING!!! now <str> - NOT null-terminated string! It is pointer to char array with <str_len> characters count

        }
        // objType.p_enum
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_enum"))
        {

               if (jstp_rx_cmp_str(arg_str,++arg_tokens,"item1")) // <- item11
               {
                // item11
            }
               else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item2")) // <- item12
               {
                // item12
            }
               else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item3")) // <- item13
               {
                // item13
            }
            else return JSTP_ARGS_ERROR; 

        }
        // objType.p_arr
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_arr"))
        {

            // Array
            size_t size;
            if (!jstp_rx_array(arg_str,arg_tokens,&size)) return JSTP_ARGS_ERROR;
            while(size--)
            {
        // objType is array of 

            // UNKNOWN TYPE


            }

        }
        // objType.p_obj
        else if (jstp_rx_cmp_str(arg_str,arg_tokens,"p_obj"))
        {

            // Object
            // Generator not supported more then one nested property

        }
        else return JSTP_ARGS_ERROR;
        arg_tokens++;
    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // objType
    jstp_tx_obj_begin();            // <- {
    jstp_tx_obj_key("p_bool");        // <- key
    // jstp_tx_bool(<int>);            // <- value
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_int");        // <- key
    // jstp_tx_long(<int>);            // <- value
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_real");        // <- key
    // jstp_tx_float(<float>);         // <- value
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_str");        // <- key
    // jstp_tx_str(<str>);            // <- value
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_enum");        // <- key
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_arr");        // <- key
    // Array
    // Generator not supported more then one nested property
    jstp_tx_obj_end_item();            // end prop

    jstp_tx_obj_key("p_obj");        // <- key
    // Object
    // Generator not supported more then one nested property

    jstp_tx_obj_end();
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.arrBool
 * arrBool -> arrBool
 * Arg      : boolArr
 * Result   : boolArr
 */
static int jstp_test_arrBool(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // boolArr is array of Bool

        int boolArg;
        if (!jstp_rx_bool(arg_str,++arg_tokens,&boolArg)) return JSTP_ARGS_ERROR;
        if (boolArg)
        {
            // true
        }else
        {
            // false
        };


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.intArr
 * intArr -> intArr
 * Arg      : intArr
 * Result   : intArr
 */
static int jstp_test_intArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // intArr is array of s8

        long intArg;
        if (!jstp_rx_long(arg_str,++arg_tokens,&intArg)) return JSTP_ARGS_ERROR;


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.realArr
 * realArr -> realArr
 * Arg      : realArr
 * Result   : realArr
 */
static int jstp_test_realArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // realArr is array of Real

        float value;
        if (!jstp_rx_float(arg_str,++arg_tokens,&value)) return JSTP_ARGS_ERROR;


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.strArr
 * strArr -> strArr
 * Arg      : strArr
 * Result   : strArr
 */
static int jstp_test_strArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // strArr is array of Version
            // string
        char * str;
        size_t str_len;
        if (!jstp_rx_str(arg_str,++arg_tokens,&str,&str_len)) return JSTP_ARGS_ERROR;
        // WARNING!!! now <str> - NOT null-terminated string! It is pointer to char array with <str_len> characters count


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.enumArr
 * enumArr -> enumArr
 * Arg      : enumArr
 * Result   : enumArr
 */
static int jstp_test_enumArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // enumArr is array of enumType

            if (jstp_rx_cmp_str(arg_str,++arg_tokens,"item1")) // <- item11
            {
                // item11
            }
            else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item2")) // <- item12
            {
                // item12
            }
            else if (jstp_rx_cmp_str(arg_str,arg_tokens,"item3")) // <- item13
            {
                // item13
            }
            else return JSTP_ARGS_ERROR; 


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.objArr
 * objArr -> objArr
 * Arg      : objArr
 * Result   : objArr
 */
static int jstp_test_objArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // objArr is array of InterfaceID

        // Generator not supported ARRAY of OBJECT


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}

/**
 * test.arrArr
 * arrArr -> arrArr
 * Arg      : arrArr
 * Result   : arrArr
 */
static int jstp_test_arrArr(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    // ======= BEGIN ARGS =======

    // Array
    size_t size;
    if (!jstp_rx_array(arg_str,arg_tokens++,&size)) return JSTP_ARGS_ERROR;
    while(size--)
    {
        // arrArr is array of intArr

            // UNKNOWN TYPE


    }

    // ======= END ARGS =======


    // BY DEFAULT RETURN 'NOT IMPLEMENTED'
    return JSTP_ITEM_NOT_IMPLEMENTED;    // <- REMOVE THIS



    // ======= BEGIN RESULT =======
    jstp_tx_begin();                // <- {"OK":

    // UNKNOWN TYPE
    jstp_tx_end();        // <- }\n
    return JSTP_NO_ERROR; // <- SUCCESS
    // ======= END RESULT =======



}



static int jstp__root_path(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    jstp_tx_begin();
    jstp_tx_array_begin();
    jstp_tx_str("info");
   jstp_tx_array_end_item();
    jstp_tx_str("test");

    jstp_tx_array_end();
    jstp_tx_end();
    return JSTP_NO_ERROR;
}


/**
 * info : DeviceInfo 1.0.0
 * Device info
 */

static int jstp_info(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    jstp_tx_begin();
    jstp_tx_str("DeviceInfo 1.0.0");
    jstp_tx_end();
    return JSTP_NO_ERROR;
}


/**
 * test : Test 1.0.0
 * Test interface
 */

static int jstp_test(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    jstp_tx_begin();
    jstp_tx_str("Test 1.0.0");
    jstp_tx_end();
    return JSTP_NO_ERROR;
}


int jstp_execute_gen(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count)
{
    if (jstp_str_compare(path_str,""))
    {
        return jstp__root_path(path_str,arg_str,arg_tokens,args_token_count);
    }


    if (jstp_str_compare(path_str,"info"))
    {
        return jstp_info(path_str,arg_str,arg_tokens,args_token_count);
    }
    if (jstp_str_compare(path_str,"info.company"))
    {
        return jstp_info_company(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.name"))
    {
        return jstp_info_name(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.sn"))
    {
        return jstp_info_sn(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.date"))
    {
        return jstp_info_date(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.sv"))
    {
        return jstp_info_sv(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.hv"))
    {
        return jstp_info_hv(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.title"))
    {
        return jstp_info_title(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"info.desc"))
    {
        return jstp_info_desc(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test"))
    {
        return jstp_test(path_str,arg_str,arg_tokens,args_token_count);
    }
    if (jstp_str_compare(path_str,"test.int"))
    {
        return jstp_test_int(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.real"))
    {
        return jstp_test_real(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.enum"))
    {
        return jstp_test_enum(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.bool"))
    {
        return jstp_test_bool(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.obj"))
    {
        return jstp_test_obj(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.arrbool"))
    {
        return jstp_test_arrBool(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.intarr"))
    {
        return jstp_test_intArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.realarr"))
    {
        return jstp_test_realArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.strarr"))
    {
        return jstp_test_strArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.enumarr"))
    {
        return jstp_test_enumArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.objarr"))
    {
        return jstp_test_objArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            
    if (jstp_str_compare(path_str,"test.arrarr"))
    {
        return jstp_test_arrArr(path_str,arg_str,arg_tokens,args_token_count);
    }
            

        
    return JSTP_PATH_NOT_FOUND;
}




