#ifndef __JSTP_GEN_H_
#define __JSTP_GEN_H_

/**
 *    This code was generated by JSTP CodeGen version 1.0.0.23341
 *
 *    Generate info:
 *        Date      : 15.09.2015 12:58
 *        User      : 
 *        Domain    : 
 *	Paths:
 *
 *		======== Device info ========
 *    	info: DeviceInfo 1.0.0
 *        info.company : Company name
 *        info.name : Model name
 *        info.sn : Serial number
 *        info.date : Production date
 *        info.sv : Firmware version
 *        info.hv : Hardware version
 *        info.title : Device title
 *        info.desc : Description
 *
 *		======== Test interface ========
 *    	test: Test 1.0.0
 *        test.int : u8 -> u8
 *        test.real : Real -> Real
 *        test.enum : enum -> enum
 *        test.bool : bool -> bool
 *        test.obj : obj -> obj
 *        test.arrBool : arrBool -> arrBool
 *        test.intArr : intArr -> intArr
 *        test.realArr : realArr -> realArr
 *        test.strArr : strArr -> strArr
 *        test.enumArr : enumArr -> enumArr
 *        test.objArr : objArr -> objArr
 *        test.arrArr : arrArr -> arrArr
*/

#include "jsmn.h"       // <-- json parser lib (https://bitbucket.org/zserge/jsmn/wiki/Home)
#include "jstp.h"       // <-- json simple text protocol lib


#ifdef __cplusplus
extern "C" {
#endif

int jstp_execute_gen(char *path_str, char* arg_str, jsmntok_t *arg_tokens, size_t args_token_count);

#ifdef __cplusplus
}
#endif

#endif /* __JSTP_GEN_H_ */
